"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useQuery } from "@tanstack/react-query";
import { NetIcon, NetworkBanner, NetworkShell, networkDate, title } from "../../../components/network-scanner/NetworkScannerUi";
import { useAuth } from "../../../hooks/useAuth";
import { toast } from "../../../lib/toast";
import { NetworkScannerService, toNetworkScannerApiError } from "../../../services/network-scanner.service";
import type { NetworkInventoryAsset, NetworkInventoryService } from "../../../features/network-scanner/types";

function serviceText(service: NetworkInventoryService) { return [`${service.port || ""}${service.protocol ? `/${service.protocol}` : ""}`, [service.name, service.product, service.version].filter(Boolean).join(" ")].filter(Boolean).join(" / ") || "Service reported"; }
function csv(value: unknown) { const text = String(value ?? ""); const safe = /^[\u0000-\u0020]*[=+\-@]/.test(text) ? `'${text}` : text; return `"${safe.replaceAll('"','""')}"`; }
function saveCsv(assets: NetworkInventoryAsset[], page: number) { const rows = [["Asset ID","Hostname","IP address","MAC address","Vendor","Device type","Operating system","Services","Network","Source agent","First seen","Last seen"], ...assets.map((asset) => [asset.id,asset.hostname,asset.ipAddress,asset.macAddress,asset.vendor,asset.deviceType,asset.operatingSystem,asset.services.map(serviceText).join("; "),asset.site,asset.sourceAgentId,asset.firstSeenAt,asset.lastSeenAt])]; const blob=new Blob(["\uFEFF",rows.map((row)=>row.map(csv).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const link=document.createElement("a"); link.href=url; link.download=`forgesec-network-inventory-page-${page}.csv`; link.click(); URL.revokeObjectURL(url); }
function age(seconds: number | null) { if (seconds === null) return "Not reported"; if (seconds < 60) return `${seconds} sec ago`; if (seconds < 3600) return `${Math.floor(seconds/60)} min ago`; if (seconds < 86400) return `${Math.floor(seconds/3600)} hr ago`; return `${Math.floor(seconds/86400)} days ago`; }

export default function NetworkInventoryPage() {
  const { user,isAuthenticated,isLoading:authLoading }=useAuth(); const [draft,setDraft]=useState(""); const [search,setSearch]=useState(""); const [siteId,setSiteId]=useState(""); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(100); const [selectedId,setSelectedId]=useState<string|null>(null);
  const inventoryQuery=useQuery({enabled:isAuthenticated,queryKey:["network-scanner","inventory",page,pageSize,search,siteId],queryFn:()=>NetworkScannerService.getInventoryPage({page,pageSize,...(search?{search}:{}),...(siteId?{siteId}:{})}),refetchInterval:30_000,placeholderData:(previous)=>previous,retry:false});
  const sitesQuery=useQuery({enabled:isAuthenticated,queryKey:["network-scanner","sites"],queryFn:()=>NetworkScannerService.listSites(),staleTime:60_000,retry:false}); const agentsQuery=useQuery({enabled:isAuthenticated,queryKey:["network-scanner","agents"],queryFn:()=>NetworkScannerService.listAgents(),refetchInterval:15_000,retry:false});
  const error=inventoryQuery.error||sitesQuery.error||agentsQuery.error; const errorMessage=error?toNetworkScannerApiError(error).message:null; useEffect(()=>{if(errorMessage)toast.error(errorMessage,"Network Inventory");},[errorMessage]);
  const assets=useMemo(()=>inventoryQuery.data?.assets||[],[inventoryQuery.data]); const total=inventoryQuery.data?.total||0; const pages=Math.max(1,Math.ceil(total/pageSize)); const summary=inventoryQuery.data?.summary; const sites=(sitesQuery.data||[]).filter((item)=>item.isActive); const selected=assets.find((item)=>item.id===selectedId)||assets[0]||null; const agent=selected?(agentsQuery.data||[]).find((item)=>item.id===selected.sourceAgentId):null; const loading=inventoryQuery.isLoading||sitesQuery.isLoading||agentsQuery.isLoading;
  if(authLoading||(!isAuthenticated&&!user))return <main className="scanner-auth-wait"><span>Opening Network Inventory...</span></main>;
  function submit(event:FormEvent){event.preventDefault();setSearch(draft.trim());setPage(1);} function clear(){setDraft("");setSearch("");setSiteId("");setPage(1);}
  return <NetworkShell active="network-inventory" user={user}><header className="network-page-header"><div><span><NetIcon name="boxes"/> Network Scanner</span><h1>Network inventory</h1><p>Explore device identity, addresses, manufacturer, type, operating system, and services reported by your agents.</p></div><nav><button className="primary" disabled={!assets.length} onClick={()=>{saveCsv(assets,page);toast.success(`${assets.length} devices exported.`,"Inventory CSV");}}><NetIcon name="download"/> Export current page CSV</button></nav></header>
    <div className="network-content"><NetworkBanner error={errorMessage} loading={loading} empty={!loading&&!errorMessage&&!total}/><section className="network-kpis">{[["Matching devices",total,`${assets.length} shown on page ${page}`,"server"],["Recently seen",summary?.activeAssets||0,"Inside the server freshness window","boxes"],["Stale devices",summary?.staleAssets||0,"Known devices not seen recently","refresh"],["Vendor identified",summary?.vendorIdentified||0,"Devices with a manufacturer","network"]].map(([label,value,detail,icon])=><article key={String(label)}><i><NetIcon name={String(icon)}/></i><span>{label}</span><strong>{loading?"Loading":value}</strong><small>{detail}</small></article>)}</section>
      <section className="network-filters"><header><i><NetIcon name="search"/></i><div><h2>Find a device</h2><p>The server searches IP address, hostname, and MAC address across the selected network.</p></div>{search||siteId?<button onClick={clear}><NetIcon name="refresh"/> Clear filters</button>:null}</header><form onSubmit={submit}><label><span>Search</span><input onChange={(event)=>setDraft(event.target.value)} placeholder="IP, hostname, or MAC" value={draft}/></label><label><span>Network</span><select onChange={(event)=>{setSiteId(event.target.value);setPage(1);}} value={siteId}><option value="">All networks</option>{sites.map((site)=><option key={site.id} value={site.id}>{site.name}{site.allowedNetworks[0]?` - ${site.allowedNetworks[0]}`:""}</option>)}</select></label><label><span>Rows per page</span><select onChange={(event)=>{setPageSize(Number(event.target.value));setPage(1);}} value={pageSize}>{[50,100,250,500].map((value)=><option key={value}>{value}</option>)}</select></label><button className="primary"><NetIcon name="search"/> Search</button></form><footer><span>Showing <b>{assets.length}</b> devices on page {page} of {pages} ({total} matching).</span><div><button disabled={page<=1||inventoryQuery.isFetching} onClick={()=>setPage((value)=>value-1)}>Previous</button><button disabled={page>=pages||inventoryQuery.isFetching} onClick={()=>setPage((value)=>value+1)}>Next</button></div></footer></section>
      <div className="network-inventory-grid"><section className="network-table"><table><thead><tr><th>Device / IP</th><th>MAC / vendor</th><th>Type / OS</th><th>Reported services</th><th>Network</th><th>Last seen</th></tr></thead><tbody>{assets.length?assets.map((asset)=><tr className={selected?.id===asset.id?"selected":""} key={asset.id}><td><button onClick={()=>setSelectedId(asset.id)}><b>{asset.hostname}</b><small>{asset.ipAddress}</small></button></td><td><code>{asset.macAddress}</code><small>{asset.vendor}</small></td><td><b>{asset.deviceType}</b><small>{asset.operatingSystem}</small></td><td><div className="network-services">{asset.services.length?asset.services.slice(0,3).map((service,index)=><span key={`${service.port}-${index}`}>{serviceText(service)}</span>):<em>None reported</em>}{asset.services.length>3&&<span>+{asset.services.length-3} more</span>}</div></td><td>{asset.site}</td><td><span className={`freshness ${asset.freshness}`}>{asset.freshness==="active"?"Recently seen":title(asset.freshness)}</span><small>{networkDate(asset.lastSeenAt)}</small></td></tr>):<tr><td className="network-table-empty" colSpan={6}>No devices match this view.</td></tr>}</tbody></table></section>
        <aside className="network-detail">{selected?<><header><span>Device details</span><h2>{selected.hostname}</h2><p>{selected.ipAddress}</p></header><dl className="inventory-facts">{[["MAC address",selected.macAddress],["Vendor",selected.vendor],["Device type",selected.deviceType],["Operating system",selected.operatingSystem],["Network",selected.site],["Agent",agent?.name||selected.sourceAgentId],["Observation source",(selected.observationSources||[]).map(title).join(" + ")||"Not reported"],["Interface",selected.interfaceName||"Not reported"],["Confidence",selected.confidence==null?"Not reported":`${Math.round(selected.confidence*100)}%`],["Freshness",title(selected.freshness)],["Observation age",age(selected.ageSeconds)],["First seen",networkDate(selected.firstSeenAt)],["Last seen",networkDate(selected.lastSeenAt)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><section className="inventory-services"><h3>Reported services ({selected.services.length})</h3>{selected.services.length?<ul>{selected.services.map((service,index)=><li key={`${service.port}-${index}`}><b>{serviceText(service)}</b>{service.state&&<small>State: {title(service.state)}</small>}</li>)}</ul>:<p>No services were reported for this device.</p>}</section><p className="network-detail-note">This view shows agent-reported inventory evidence. A device classification or service is not, by itself, a vulnerability finding.</p></>:<div className="network-empty"><NetIcon name="boxes"/><span>Select a device to inspect its reported metadata.</span></div>}</aside>
      </div></div></NetworkShell>;
}
