"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import SubscriptionSidebar from "../../../components/dashboard/SubscriptionSidebar";
import { useAuth } from "../../../hooks/useAuth";
import { getApiErrorMessage } from "../../../lib/api-error";
import { toast } from "../../../lib/toast";
import { KnowledgeBaseService, type KnowledgeBaseEntry, type KnowledgeBaseSummary } from "../../../services/knowledge-base.service";

type StatusFilter = "all" | "enabled" | "disabled";
type SafetyFilter = "all" | "ready" | "review";
type SortMode = "cve" | "updated" | "filename" | "timeout";
const PAGE_SIZE = 12;
const EMPTY_SUMMARY: KnowledgeBaseSummary = { total: 0, enabled: 0, safe: 0, python: 0, compatibility_ready: 0, compatibility_review: 0, compatibility_disabled: 0, runnable: 0, runner_review: 0, runner_disabled: 0 };
function Icon({ children }: { children: ReactNode }) { return <svg aria-hidden="true" viewBox="0 0 24 24">{children}</svg>; }
const icons = { database: <Icon><ellipse cx="12" cy="5" rx="8" ry="3" /><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6" /></Icon>, shield: <Icon><path d="M12 3 5 6v5c0 4.5 2.8 8 7 10 4.2-2 7-5.5 7-10V6l-7-3Z" /><path d="m9 12 2 2 4-5" /></Icon>, code: <Icon><path d="m8 8-4 4 4 4m8-8 4 4-4 4M14 4l-4 16" /></Icon>, clock: <Icon><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></Icon>, refresh: <Icon><path d="M20 7v5h-5M4 17v-5h5" /><path d="M18.5 9A7 7 0 0 0 6 6.5M5.5 15A7 7 0 0 0 18 17.5" /></Icon>, download: <Icon><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 19h14" /></Icon>, play: <Icon><path d="m8 5 11 7-11 7V5Z" /></Icon>, eye: <Icon><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z" /><circle cx="12" cy="12" r="2.5" /></Icon> };
function cve(entry: KnowledgeBaseEntry) { return entry.cve_id || entry.cve || "UNKNOWN-CVE"; }
function args(entry: KnowledgeBaseEntry) { const value = entry.default_args?.argv_template; return Array.isArray(value) ? value.map(String).join(" ") : "-"; }
function date(value?: string | null) { if (!value) return "-"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleDateString([], { day: "2-digit", month: "short", year: "numeric" }); }
function number(value: unknown) { const result = Number(value || 0); return Number.isFinite(result) ? result : 0; }
function runState(entry: KnowledgeBaseEntry) { const status = String(entry.compatibility_status || entry.metadata?.compatibility_status || "").toLowerCase(); if (!entry.is_enabled || status === "disabled") return "disabled"; if (entry.is_runnable || entry.is_safe_to_run && status === "ready") return "ready"; return "review"; }
function csvCell(value: unknown) { const text = String(value ?? ""); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
function exportCsv(rows: KnowledgeBaseEntry[]) { const header = ["CVE", "Script", "Path", "Type", "Enabled", "Safe To Run", "Timeout", "Arguments", "Updated"]; const body = rows.map((row) => [cve(row), row.script_filename, row.script_path, row.script_type, row.is_enabled, row.is_safe_to_run, row.default_timeout_seconds, args(row), row.updated_at].map(csvCell).join(",")); const blob = new Blob([[header.join(","), ...body].join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "ai-pentest-knowledge-base.csv"; link.click(); URL.revokeObjectURL(url); }

export default function KnowledgeBasePage() {
  const { user, isAuthenticated, isLoading: authLoading } = useAuth();
  const [search, setSearch] = useState(""); const [query, setQuery] = useState(""); const [page, setPage] = useState(1);
  const [status, setStatus] = useState<StatusFilter>("all"); const [safety, setSafety] = useState<SafetyFilter>("all"); const [type, setType] = useState("all"); const [sort, setSort] = useState<SortMode>("cve");
  const [entries, setEntries] = useState<KnowledgeBaseEntry[]>([]); const [summary, setSummary] = useState(EMPTY_SUMMARY); const [pagination, setPagination] = useState({ total: 0, page: 1, page_size: PAGE_SIZE, total_pages: 1 });
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const [updated, setUpdated] = useState<string | null>(null);
  const firstLoad = useRef(true);
  useEffect(() => { const timer = window.setTimeout(() => { setQuery(search.trim()); setPage(1); }, 300); return () => window.clearTimeout(timer); }, [search]);
  useEffect(() => setPage(1), [safety, status, type]);
  const load = useCallback(async (background = false, notify = false) => { background ? setRefreshing(true) : setLoading(true); setError(null); try { const response = await KnowledgeBaseService.list({ page, pageSize: PAGE_SIZE, search: query || undefined, scriptType: type === "all" ? undefined : type, enabled: status === "all" ? "all" : status === "enabled", compatibility: safety }, background); setEntries(Array.isArray(response.data) ? response.data : []); setPagination(response.pagination || { total: 0, page, page_size: PAGE_SIZE, total_pages: 1 }); setSummary(Object.fromEntries(Object.keys(EMPTY_SUMMARY).map((key) => [key, number(response.summary?.[key as keyof KnowledgeBaseSummary])])) as KnowledgeBaseSummary); setUpdated(new Date().toISOString()); if (notify) toast.success("Knowledge base is up to date.", "Knowledge Hub"); } catch (loadError) { const message = getApiErrorMessage(loadError, "Unable to load the AI knowledge base."); setError(message); setEntries([]); toast.error(message, "Knowledge Hub"); } finally { setLoading(false); setRefreshing(false); firstLoad.current = false; } }, [page, query, safety, status, type]);
  useEffect(() => { void load(!firstLoad.current); }, [load]);
  const rows = useMemo(() => [...entries].sort((a, b) => sort === "updated" ? (Date.parse(b.updated_at || "") || 0) - (Date.parse(a.updated_at || "") || 0) : sort === "filename" ? a.script_filename.localeCompare(b.script_filename) : sort === "timeout" ? b.default_timeout_seconds - a.default_timeout_seconds : cve(a).localeCompare(cve(b))), [entries, sort]);
  const types = useMemo(() => [...new Set(entries.map((entry) => entry.script_type).filter(Boolean))].sort(), [entries]);
  const total = pagination.total || summary.total; const pages = Math.max(1, pagination.total_pages); const from = rows.length ? (pagination.page - 1) * pagination.page_size + 1 : 0; const to = rows.length ? from + rows.length - 1 : 0; const ready = summary.runnable; const readyPercent = summary.total ? Math.round(ready / summary.total * 100) : 0; const enabledPercent = summary.total ? Math.round(summary.enabled / summary.total * 100) : 0; const avgTimeout = rows.length ? Math.round(rows.reduce((sum, row) => sum + number(row.default_timeout_seconds), 0) / rows.length) : 0;
  if (authLoading || (!isAuthenticated && !user)) return <main className="scanner-auth-wait"><span>Opening AI Knowledge Hub...</span></main>;
  return <main className="dashboard-shell subscription-dashboard-shell ai-kb-shell"><SubscriptionSidebar active="ai-knowledge" user={user} /><section className="dashboard-workspace ai-kb-workspace">
    <header className="ai-kb-topbar"><div><span>{icons.code} AI Pentester Scripts</span><h1>AI Knowledge Base</h1></div><nav><button onClick={() => toast.info("Review Queue will be connected on its dedicated page.", "Knowledge Hub")}>Review Queue</button><Link href="/ai-scanner/new-scan">{icons.play} Launch Scan</Link><button disabled={!rows.length} onClick={() => exportCsv(rows)}>{icons.download} Export CSV</button><button aria-label="Refresh knowledge base" disabled={refreshing} onClick={() => void load(true, true)}>{icons.refresh}</button></nav></header>
    <div className="ai-kb-content">{error && <section className="ai-kb-alert"><strong>Knowledge base unavailable</strong><span>{error}</span><button onClick={() => void load(true)}>Try again</button></section>}
      <section className="ai-kb-metrics"><article><span>Indexed Scripts</span><strong>{total.toLocaleString()}</strong><small>CVE records in database</small><i>{icons.database}</i></article><article><span>Ready Scripts</span><strong>{ready.toLocaleString()}</strong><small>{readyPercent}% audit ready</small><i>{icons.shield}</i></article><article><span>Enabled</span><strong>{summary.enabled.toLocaleString()}</strong><small>{enabledPercent}% active</small><i>{icons.shield}</i></article><article><span>Python</span><strong>{summary.python.toLocaleString()}</strong><small>Script type</small><i>{icons.code}</i></article><article><span>Avg Timeout</span><strong>{avgTimeout}s</strong><small>Current page</small><i>{icons.clock}</i></article></section>
      <section className="ai-kb-controls"><div><header><i>{icons.shield}</i><span><h2>Runner Readiness</h2><p>{readyPercent}% ready for sandbox</p></span></header><div className="ai-kb-readiness">{[{ label: "Ready", value: ready }, { label: "Review", value: summary.runner_review }, { label: "Disabled", value: summary.runner_disabled }].map((item) => <article className={item.label.toLowerCase()} key={item.label}><span>{item.label}</span><b>{item.value}</b><i><em style={{ width: `${summary.total ? Math.round(item.value / summary.total * 100) : 0}%` }} /></i></article>)}</div></div><aside><header><h2>Library Controls</h2><span>Showing {from}-{to} of {total}</span></header><div><input aria-label="Search knowledge base" onChange={(event) => setSearch(event.target.value)} placeholder="Search CVE, script, path..." value={search} /><select aria-label="Filter enabled state" onChange={(event) => setStatus(event.target.value as StatusFilter)} value={status}><option value="all">All status</option><option value="enabled">Enabled</option><option value="disabled">Disabled</option></select><select aria-label="Filter compatibility" onChange={(event) => setSafety(event.target.value as SafetyFilter)} value={safety}><option value="all">All safety</option><option value="ready">Safe</option><option value="review">Review</option></select><select aria-label="Filter script type" onChange={(event) => setType(event.target.value)} value={type}><option value="all">All types</option>{types.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Sort knowledge base" onChange={(event) => setSort(event.target.value as SortMode)} value={sort}><option value="cve">CVE</option><option value="updated">Updated</option><option value="filename">File</option><option value="timeout">Timeout</option></select></div></aside></section>
      <section className="ai-kb-table"><header><div><h2>Script Index</h2><p>Last refreshed {updated ? new Date(updated).toLocaleString() : "-"}</p></div><span>Page {pagination.page} of {pages}</span></header><div className="ai-kb-table-wrap"><table><thead><tr><th>CVE</th><th>Script</th><th>Runner</th><th>Safety</th><th>Arguments</th><th>Updated</th><th>Action</th></tr></thead><tbody>{rows.length ? rows.map((entry) => { const state = runState(entry); return <tr key={entry.id}><td><strong>{cve(entry)}</strong></td><td><b title={entry.script_filename}>{entry.script_filename}</b><small title={entry.script_path}>{entry.script_path}</small></td><td><span>{entry.script_type}</span><em>{entry.default_timeout_seconds}s</em></td><td><i className={state}>{state}</i></td><td><code title={args(entry)}>{args(entry)}</code></td><td>{date(entry.updated_at)}</td><td><Link href={`/ai-scanner/knowledge-base/${encodeURIComponent(cve(entry))}`}>{icons.eye} View</Link></td></tr>; }) : <tr><td className="ai-kb-empty" colSpan={7}>{loading ? "Loading indexed scripts..." : "No script records match this view."}</td></tr>}</tbody></table></div><footer><span>Showing <b>{from}</b> to <b>{to}</b> of <b>{total}</b> records</span><div><button disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>Previous</button><b>{page} / {pages}</b><button disabled={page >= pages} onClick={() => setPage((value) => Math.min(pages, value + 1))}>Next</button></div></footer></section>
    </div></section></main>;
}
