"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import SubscriptionSidebar from "../../components/dashboard/SubscriptionSidebar";
import { useAuth } from "../../hooks/useAuth";
import { getApiErrorMessage } from "../../lib/api-error";
import { toast } from "../../lib/toast";
import { APIScannerService, type APIAuthType, type APIInputMode, type APIProfile, type APIScan, type APIScanCreate, type APISeverity, type APIStatus } from "../../services/api-scanner.service";

const severities: APISeverity[] = ["info", "low", "medium", "high", "critical"];
const finalStatuses: APIStatus[] = ["completed", "completed_with_warnings", "inconclusive", "failed", "canceled"];
const maxFileBytes = 10 * 1024 * 1024;
type FormState = { scanName: string; target: string; inputMode: APIInputMode; profile: APIProfile; authType: APIAuthType; authName: string; authValue: string; username: string; password: string; apiKeyLocation: "header" | "query"; tags: string; selectedSeverities: APISeverity[]; safeMode: boolean; stateChanges: boolean; verifyTls: boolean; allowPrivate: boolean; authorized: boolean; concurrency: number; maxMinutes: number };
const initialForm: FormState = { scanName: "Authorized API Security Assessment", target: "", inputMode: "openapi", profile: "baseline", authType: "none", authName: "", authValue: "", username: "", password: "", apiKeyLocation: "header", tags: "", selectedSeverities: [...severities], safeMode: true, stateChanges: false, verifyTls: true, allowPrivate: false, authorized: false, concurrency: 10, maxMinutes: 60 };

function Icon({ name }: { name: "close" | "key" | "play" | "refresh" | "search" | "shield" | "upload" }) { const paths: Record<string, ReactNode> = { close: <path d="m6 6 12 12M18 6 6 18" />, key: <><circle cx="8" cy="15" r="4" /><path d="m11 12 8-8m-3 3 3 3" /></>, play: <path d="m8 5 11 7-11 7V5Z" />, refresh: <><path d="M20 7v5h-5" /><path d="M19 12a7 7 0 1 1-2-5" /></>, search: <><circle cx="11" cy="11" r="7" /><path d="m16 16 4 4" /></>, shield: <><path d="M12 3 5 6v5c0 5 3 8 7 10 4-2 7-5 7-10V6l-7-3Z" /><path d="m9 12 2 2 4-5" /></>, upload: <><path d="M12 16V4m0 0L8 8m4-4 4 4" /><path d="M5 20h14" /></> }; return <svg aria-hidden="true" fill="none" viewBox="0 0 24 24">{paths[name]}</svg>; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function date(value?: string | null) { if (!value) return "—"; const result = new Date(value); return Number.isNaN(result.getTime()) ? value : result.toLocaleString(); }
function saveBlob(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }

export default function APIScannerPage() {
  const queryClient = useQueryClient(); const { isAuthenticated, isLoading: authLoading, user } = useAuth();
  const [form, setForm] = useState<FormState>(initialForm); const [file, setFile] = useState<File | null>(null); const [fileKey, setFileKey] = useState(0);
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null);
  useEffect(() => { if (!authLoading && !isAuthenticated) window.location.replace(`/login?next=${encodeURIComponent("/api-scanner")}`); }, [authLoading, isAuthenticated]);
  const scansQuery = useQuery({ enabled: isAuthenticated, queryFn: () => APIScannerService.scans({ page, page_size: 10, ...(search.trim() ? { q: search.trim() } : {}), ...(status ? { status } : {}) }), queryKey: ["api-scanner", "scans", page, search, status], refetchInterval: 5_000, retry: false });
  const healthQuery = useQuery({ enabled: isAuthenticated, queryFn: APIScannerService.health, queryKey: ["api-scanner", "health"], refetchInterval: 15_000, retry: false });
  const detailQuery = useQuery({ enabled: Boolean(selectedId), queryFn: () => APIScannerService.detail(selectedId as string), queryKey: ["api-scanner", "detail", selectedId], refetchInterval: selectedId ? 3_000 : false, retry: false });
  useEffect(() => { if (scansQuery.error) toast.error(getApiErrorMessage(scansQuery.error, "Unable to load API scans."), "API scanner unavailable"); }, [scansQuery.error]);

  const refreshScans = () => queryClient.invalidateQueries({ queryKey: ["api-scanner", "scans"] });
  const startMutation = useMutation({ mutationFn: ({ payload, specification }: { payload: APIScanCreate; specification: File | null }) => APIScannerService.start(payload, specification), onSuccess: async (result) => { toast.success(result.message || "The scanner will run preflight first.", "API scan queued"); setForm(initialForm); setFile(null); setFileKey((value) => value + 1); setPage(1); await refreshScans(); }, onError: (error) => toast.error(getApiErrorMessage(error, "Unable to launch this API scan."), "Scan not launched") });
  const controlMutation = useMutation({ mutationFn: ({ action, scanId }: { action: "pause" | "resume" | "cancel"; scanId: string }) => APIScannerService.control(scanId, action), onSuccess: async (_, variables) => { toast.success(`The scan was ${variables.action === "cancel" ? "cancelled" : `${variables.action}d`}.`, "Scan updated"); await refreshScans(); }, onError: (error) => toast.error(getApiErrorMessage(error), "Scan update failed") });
  const deleteMutation = useMutation({ mutationFn: APIScannerService.remove, onSuccess: async () => { toast.success("The API scan and its visible evidence were removed.", "Scan removed"); await refreshScans(); }, onError: (error) => toast.error(getApiErrorMessage(error), "Remove failed") });
  const reportMutation = useMutation({ mutationFn: ({ format, scanId }: { format: "json" | "csv" | "pdf"; scanId: string }) => APIScannerService.report(scanId, format), onSuccess: (data, variables) => { const blob = data instanceof Blob ? data : new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }); saveBlob(blob, `api-security-report-${variables.scanId}.${variables.format}`); toast.success(`${variables.format.toUpperCase()} report downloaded.`, "Report ready"); }, onError: (error) => toast.error(getApiErrorMessage(error), "Report download failed") });

  const rows = scansQuery.data?.results ?? []; const pages = Math.max(1, Math.ceil((scansQuery.data?.count ?? 0) / 10));
  const metrics = useMemo(() => ({ active: rows.filter((item) => ["queued", "running", "paused"].includes(item.status)).length, completed: rows.filter((item) => ["completed", "completed_with_warnings"].includes(item.status)).length, inconclusive: rows.filter((item) => item.status === "inconclusive").length, findings: rows.reduce((sum, item) => sum + (item.findings_count ?? 0), 0) }), [rows]);
  const authReady = form.authType === "none" || (form.authType === "bearer" && Boolean(form.authValue.trim())) || (form.authType === "basic" && Boolean(form.username.trim() && form.password)) || (["api_key", "custom_header"].includes(form.authType) && Boolean(form.authName.trim() && form.authValue));
  const specReady = form.inputMode === "url" || Boolean(file); const fullReady = form.inputMode === "url" || form.profile !== "full" || !form.safeMode;
  const formReady = Boolean(form.scanName.trim() && form.target.trim() && form.selectedSeverities.length && specReady && authReady && form.authorized && fullReady && healthQuery.data?.ready);
  function authPayload(): Record<string, string> { if (form.authType === "bearer") return { token: form.authValue }; if (form.authType === "basic") return { username: form.username, password: form.password }; if (form.authType === "api_key") return { name: form.authName, value: form.authValue, location: form.apiKeyLocation }; if (form.authType === "custom_header") return { name: form.authName, value: form.authValue }; return {}; }
  function submit(event: FormEvent) { event.preventDefault(); if (!formReady) { toast.warning("Complete the required target, specification, authorization, and scanner readiness checks.", "Scan is not ready"); return; } startMutation.mutate({ specification: form.inputMode === "url" ? null : file, payload: { scan_name: form.scanName.trim(), target: form.target.trim(), input_mode: form.inputMode, scan_profile: form.profile, severity_filter: form.selectedSeverities, tags: form.tags.split(",").map((item) => item.trim()).filter(Boolean), auth_type: form.authType, auth_payload: authPayload(), authorization_confirmed: form.authorized, allow_private_targets: form.allowPrivate, safe_mode: form.safeMode, include_state_changing_operations: form.stateChanges, verify_tls: form.verifyTls, rate_limit: 50, concurrency: form.concurrency, request_timeout_seconds: 15, max_scan_seconds: form.maxMinutes * 60 } }); }
  if (authLoading || (!isAuthenticated && !user)) return <main className="scanner-auth-wait"><span>Opening secure API scanner workspace…</span></main>;

  return <main className="dashboard-shell subscription-dashboard-shell api-shell"><SubscriptionSidebar active="api-scanner" scannerCount={metrics.active} user={user} /><section className="dashboard-workspace api-workspace">
    <header className="dashboard-topbar"><div><span>{user?.tenant?.name || "Security Workspace"}</span><b>/</b><strong>API Scanner</strong></div><div className="dashboard-top-actions"><button disabled={scansQuery.isFetching} onClick={() => Promise.all([scansQuery.refetch(), healthQuery.refetch()])} type="button"><Icon name="refresh" />{scansQuery.isFetching ? "Refreshing…" : "Refresh"}</button></div></header>
    <div className="api-content"><header className="api-heading"><span>Authorized API validation</span><h1>API Scanner</h1><p>URL, OpenAPI 3, and Swagger 2 security assessment with evidence and coverage.</p></header>
      <section className="api-metrics"><Metric title="Active" value={metrics.active} detail="Queued, running, or paused"/><Metric title="Completed" value={metrics.completed} detail="Successful scans on this page"/><Metric title="Inconclusive" value={metrics.inconclusive} detail="Coverage could not be established"/><Metric title="Findings" value={metrics.findings} detail="Observed scanner evidence"/></section>
      <form className="api-card api-launch" onSubmit={submit}><header><div><h2>Launch authorized assessment</h2><p>Use an API definition for meaningful endpoint and method coverage.</p></div><Icon name="shield" /></header><div className="api-launch-grid"><section className="api-main-form"><div className="api-two"><Field label="Scan name"><input onChange={(e) => setForm((v) => ({ ...v, scanName: e.target.value }))} required value={form.scanName}/></Field><Field label="Target base URL"><input onChange={(e) => setForm((v) => ({ ...v, target: e.target.value }))} placeholder="https://api.example.com/v1" required type="url" value={form.target}/></Field></div>
        <div><b className="api-label">Input mode</b><div className="api-mode-grid">{(["openapi", "swagger", "url"] as APIInputMode[]).map((mode) => <button className={form.inputMode === mode ? "selected" : ""} key={mode} onClick={() => { setForm((v) => ({ ...v, inputMode: mode })); setFile(null); setFileKey((v) => v + 1); }} type="button"><strong>{mode === "openapi" ? "OpenAPI 3" : mode === "swagger" ? "Swagger 2" : "URL only"}</strong><small>{mode === "url" ? "Host-level templates; limited route coverage" : "Upload JSON or YAML, maximum 10 MB / 2,000 operations"}</small></button>)}</div></div>
        {form.inputMode !== "url" ? <label className="api-upload"><Icon name="upload"/><strong>{file?.name || `Choose ${form.inputMode === "openapi" ? "OpenAPI 3" : "Swagger 2"} JSON/YAML`}</strong><small>Remote $ref documents are rejected. Secrets must not be embedded in the specification.</small><input accept=".json,.yaml,.yml,application/json,application/yaml,text/yaml" key={fileKey} onChange={(e) => { const next = e.target.files?.[0] ?? null; if (next && next.size > maxFileBytes) { toast.warning("The API specification exceeds the 10 MB limit.", "File too large"); e.target.value = ""; return; } setFile(next); }} required type="file"/></label> : <div className="api-notice warning">URL-only mode cannot prove every API route or HTTP method was tested. Prefer OpenAPI or Swagger when available.</div>}
        <div className="api-two"><Field label="Scan profile"><select onChange={(e) => setForm((v) => ({ ...v, profile: e.target.value as APIProfile, stateChanges: e.target.value === "full" ? v.stateChanges : false }))} value={form.profile}><option value="discovery">Discovery</option><option value="baseline">Baseline</option><option value="full">Full</option></select></Field><Field label="Optional template tags"><input onChange={(e) => setForm((v) => ({ ...v, tags: e.target.value }))} placeholder="Leave blank for broad coverage" value={form.tags}/></Field><Field label="Request concurrency"><input max={50} min={1} onChange={(e) => setForm((v) => ({ ...v, concurrency: Math.min(50, Math.max(1, Number(e.target.value) || 1)) }))} type="number" value={form.concurrency}/><small>Parallel requests, maximum 50.</small></Field><Field label="Maximum engine runtime"><input max={360} min={15} onChange={(e) => setForm((v) => ({ ...v, maxMinutes: Math.min(360, Math.max(15, Number(e.target.value) || 15)) }))} type="number" value={form.maxMinutes}/><small>Minutes per engine, maximum 360.</small></Field></div>
        <div className={`api-notice ${form.profile === "full" ? "danger" : "info"}`}>{form.profile === "discovery" ? "Discovery parses the contract only and does not send vulnerability payloads." : form.profile === "baseline" ? "Baseline executes schema-derived read-only requests and safe templates." : "Full runs active API testing. Use only against an isolated target you are authorized to test."}</div>
        <div><div className="api-severity-head"><b className="api-label">Included severities</b><span>{form.selectedSeverities.length} selected</span></div><div className="api-severities">{severities.map((item) => <button className={form.selectedSeverities.includes(item) ? "selected" : ""} key={item} onClick={() => setForm((v) => ({ ...v, selectedSeverities: v.selectedSeverities.includes(item) ? v.selectedSeverities.filter((value) => value !== item) : [...v.selectedSeverities, item] }))} type="button">{label(item)}</button>)}</div></div>
      </section><aside className="api-auth"><h3><Icon name="key"/>Authentication</h3><Field label="Method"><select onChange={(e) => setForm((v) => ({ ...v, authType: e.target.value as APIAuthType, authName: "", authValue: "", username: "", password: "" }))} value={form.authType}><option value="none">No authentication</option><option value="bearer">Bearer token</option><option value="basic">Basic authentication</option><option value="api_key">API key</option><option value="custom_header">Custom auth header</option></select></Field>
        {form.authType === "bearer" && <Field label="Token"><input autoComplete="off" onChange={(e) => setForm((v) => ({ ...v, authValue: e.target.value }))} type="password" value={form.authValue}/></Field>}{form.authType === "basic" && <div className="api-two"><Field label="Username"><input onChange={(e) => setForm((v) => ({ ...v, username: e.target.value }))} value={form.username}/></Field><Field label="Password"><input onChange={(e) => setForm((v) => ({ ...v, password: e.target.value }))} type="password" value={form.password}/></Field></div>}{["api_key", "custom_header"].includes(form.authType) && <><Field label="Header / parameter name"><input onChange={(e) => setForm((v) => ({ ...v, authName: e.target.value }))} placeholder="X-API-Key" value={form.authName}/></Field><Field label="Secret value"><input onChange={(e) => setForm((v) => ({ ...v, authValue: e.target.value }))} type="password" value={form.authValue}/></Field>{form.authType === "api_key" && <select onChange={(e) => setForm((v) => ({ ...v, apiKeyLocation: e.target.value as "header" | "query" }))} value={form.apiKeyLocation}><option value="header">Send in header</option><option value="query">Send in query</option></select>}</>}
        <p>Credentials are encrypted by the backend and redacted from findings and reports.</p><div className="api-checks"><Check checked={form.safeMode} onChange={(checked) => setForm((v) => ({ ...v, safeMode: checked, stateChanges: checked ? false : v.stateChanges }))}>Safe mode (exclude intrusive/fuzz/DoS tags)</Check><Check checked={form.verifyTls} onChange={(checked) => setForm((v) => ({ ...v, verifyTls: checked }))}>Verify TLS certificates</Check><Check checked={form.allowPrivate} onChange={(checked) => setForm((v) => ({ ...v, allowPrivate: checked }))}>Approve private/local targets</Check><Check boxed checked={form.stateChanges} disabled={form.profile !== "full" || form.safeMode} onChange={(checked) => setForm((v) => ({ ...v, stateChanges: checked }))}>Exercise documented state-changing operations. This may create, modify, or delete target data.</Check><Check boxed danger checked={form.authorized} onChange={(checked) => setForm((v) => ({ ...v, authorized: checked }))}>I confirm that my organization owns this target or has explicit written authorization to test it.</Check></div>
        <button className="api-launch-button" disabled={!formReady || startMutation.isPending} type="submit"><Icon name="play"/>{startMutation.isPending ? "Launching…" : "Launch API scan"}</button>{!healthQuery.data?.ready && <strong className="api-error">API scanner service is not ready. Start the scanner and try again.</strong>}{!fullReady && <strong className="api-error">Full specification testing requires safe mode to be disabled.</strong>}
      </aside></div></form>
      <section className="api-card api-history"><header><div><h2>Scan history</h2><p>Live state, reachability, evidence count, and reports.</p></div><div><label><Icon name="search"/><input onChange={(e) => { setPage(1); setSearch(e.target.value); }} placeholder="Search name or target" value={search}/></label><select onChange={(e) => { setPage(1); setStatus(e.target.value); }} value={status}><option value="">All states</option>{["queued", "running", "paused", ...finalStatuses].map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></div></header><div className="api-table"><table><thead><tr><th>Scan</th><th>Target / input</th><th>State</th><th>Coverage</th><th>Findings</th><th>Timeline</th><th>Actions</th></tr></thead><tbody>{scansQuery.isLoading ? <tr><td colSpan={7}>Loading API scans…</td></tr> : !rows.length ? <tr><td className="empty" colSpan={7}>No API scans match this view.</td></tr> : rows.map((scan) => <ScanRow busy={controlMutation.isPending || deleteMutation.isPending || reportMutation.isPending} key={scan.id} onControl={(action) => controlMutation.mutate({ scanId: scan.id, action })} onDelete={() => window.confirm(`Delete ${scan.scan_name}?`) && deleteMutation.mutate(scan.id)} onReport={(format) => reportMutation.mutate({ scanId: scan.id, format })} onView={() => setSelectedId(scan.id)} scan={scan}/>)}</tbody></table></div><footer><span>{scansQuery.data?.count ?? 0} total scans</span><div><button disabled={page <= 1} onClick={() => setPage((v) => v - 1)} type="button">Previous</button><b>{page} / {pages}</b><button disabled={page >= pages} onClick={() => setPage((v) => v + 1)} type="button">Next</button></div></footer></section>
    </div></section>{selectedId && <DetailModal detail={detailQuery.data} loading={detailQuery.isLoading} onClose={() => setSelectedId(null)}/>}</main>;
}

function Metric({ detail, title, value }: { detail: string; title: string; value: number }) { return <article><span>{title}</span><strong>{value}</strong><small>{detail}</small></article>; }
function Field({ children, label: title }: { children: ReactNode; label: string }) { return <label className="api-field"><span>{title}</span>{children}</label>; }
function Check({ boxed, checked, children, danger, disabled, onChange }: { boxed?: boolean; checked: boolean; children: ReactNode; danger?: boolean; disabled?: boolean; onChange: (checked: boolean) => void }) { return <label className={`${boxed ? "boxed" : ""}${danger ? " danger" : ""}`}><input checked={checked} disabled={disabled} onChange={(e) => onChange(e.target.checked)} type="checkbox"/><span>{children}</span></label>; }
function ScanRow({ busy, onControl, onDelete, onReport, onView, scan }: { busy: boolean; onControl: (action: "pause" | "resume" | "cancel") => void; onDelete: () => void; onReport: (format: "json" | "csv" | "pdf") => void; onView: () => void; scan: APIScan }) { const final = finalStatuses.includes(scan.status); const coverage = scan.coverage?.operations; return <tr><td><strong>{scan.scan_name}</strong><small>{scan.id}</small></td><td><strong>{scan.target}</strong><small>{label(scan.input_mode)} · {label(scan.scan_profile)}</small></td><td><span className={`api-status ${scan.status}`}>{label(scan.status)}</span><small>{label(scan.stage || "queued")} · {scan.progress}%</small></td><td><strong>{coverage ? `${coverage.completed ?? 0} / ${coverage.discovered ?? 0}` : scan.input_mode === "url" ? "Host checks" : "Not measured"}</strong><small>{coverage ? "completed / discovered" : "coverage unavailable"}</small></td><td><b className="api-finding-count">{scan.findings_count ?? 0}</b></td><td><small>Start: {date(scan.started_at)}</small><small>End: {date(scan.completed_at)}</small></td><td><div className="api-actions"><button onClick={onView} type="button">View</button>{(["json", "csv", "pdf"] as const).map((format) => <button disabled={!final || busy} key={format} onClick={() => onReport(format)} type="button">{format}</button>)}{scan.status === "running" && <button onClick={() => onControl("pause")} type="button">Pause</button>}{scan.status === "paused" && <button onClick={() => onControl("resume")} type="button">Resume</button>}{["queued", "running", "paused"].includes(scan.status) && <button onClick={() => onControl("cancel")} type="button">Cancel</button>}<button className="danger" disabled={busy} onClick={onDelete} type="button">Delete</button></div></td></tr>; }
function DetailModal({ detail, loading, onClose }: { detail: Awaited<ReturnType<typeof APIScannerService.detail>> | undefined; loading: boolean; onClose: () => void }) { const operations = detail?.coverage?.operations; return <div className="api-modal-backdrop"><section className="api-detail-modal"><header><div><span>API scan evidence</span><h2>{detail?.scan_name || "Loading scan…"}</h2><p>{detail?.target}</p></div><button aria-label="Close" onClick={onClose} type="button"><Icon name="close"/></button></header><div className="api-detail-body">{loading ? <div className="api-detail-empty">Loading evidence…</div> : detail && <><section className="api-detail-metrics"><Metric title="Progress" value={detail.progress} detail={label(detail.status)}/><Metric title="Discovered" value={operations?.discovered ?? 0} detail="Spec operations"/><Metric title="Completed" value={operations?.completed ?? 0} detail="Engine coverage"/><Metric title="Findings" value={detail.findings_count ?? 0} detail="Deduplicated evidence"/></section>{detail.error_message && <div className="api-notice danger">{detail.error_message}</div>}<section><h3>Findings</h3><div className="api-detail-list">{detail.findings?.length ? detail.findings.map((finding) => <article key={finding.id}><header><strong>{finding.name}</strong><span>{finding.severity}</span></header><small>{finding.template_id} · {finding.matched_at || finding.host}</small>{finding.description && <p>{finding.description}</p>}{finding.remediation && <p><b>Remediation:</b> {finding.remediation}</p>}{finding.evidence && <details><summary>Request / response evidence</summary><pre>{JSON.stringify(finding.evidence, null, 2)}</pre></details>}</article>) : <div className="api-detail-empty">No finding evidence was recorded. Confirm operation and engine coverage.</div>}</div></section><section><h3>Execution timeline</h3><div className="api-events">{detail.events?.map((event, index) => <article key={`${event.timestamp}-${index}`}><strong>{label(event.stage)}</strong><time>{date(event.timestamp)}</time><p>{event.message}</p></article>)}</div></section><section><h3>Diagnostics</h3><pre className="api-diagnostics">{JSON.stringify(detail.diagnostics ?? {}, null, 2)}</pre></section></>}</div></section></div>; }
